const listaDeLibros = [
  {
    titulo: 'Cien años de soledad',
    autor: 'Gabriel García Márquez',
    genero: 'Realismo mágico',
    año: 1967,
  },
  {
    titulo: 'Crónica de una muerte anunciada',
    autor: 'Gabriel García Márquez',
    genero: 'Ficción',
    año: 1981,
  },
  {
    titulo: 'El otoño del patriarca',
    autor: 'Gabriel García Márquez',
    genero: 'Realismo mágico',
    año: 1975,
  },
  {
    titulo: '1984',
    autor: 'George Orwell',
    genero: 'Ficción política',
    año: 1949,
  },
  {
    titulo: 'El señor de los anillos',
    autor: 'J.R.R. Tolkien',
    genero: 'Fantasía',
    año: 1954,
  },
  {
    titulo: 'The Name of the Wind',
    autor: 'Patrick Rothfuss',
    genero: 'Fantasía',
    año: 2007,
  },
  {
    titulo: 'To Kill a Mockingbird',
    autor: 'Harper Lee',
    genero: 'Novela social',
    año: 1960,
  },
  {
    titulo: 'La Odisea',
    autor: 'Homero',
    genero: 'Epopeya',
    año: -800,
  },
  {
    titulo: 'La isla del tesoro',
    autor: 'Robert Louis Stevenson',
    genero: 'Aventura',
    año: 1883,
  },
  {
    titulo: 'El conde de Montecristo',
    autor: 'Alejandro Dumas',
    genero: 'Aventura',
    año: 1844,
  },
  {
    titulo: 'El retrato de Dorian Gray',
    autor: 'Oscar Wilde',
    genero: 'Ficción gótica',
    año: 1890,
  },
  {
    titulo: 'Drácula',
    autor: 'Bram Stoker',
    genero: 'Ficción gótica',
    año: 1897,
  },
  {
    titulo: 'El guardián entre el centeno',
    autor: 'J.D. Salinger',
    genero: 'Novela de iniciación',
    año: 1951,
  },
  {
    titulo: 'Matar un ruiseñor',
    autor: 'Harper Lee',
    genero: 'Novela social',
    año: 1960,
  },
  {
    titulo: 'El gran Gatsby',
    autor: 'F. Scott Fitzgerald',
    genero: 'Novela de época',
    año: 1925,
  },
  {
    titulo: 'Moby Dick',
    autor: 'Herman Melville',
    genero: 'Novela de aventuras',
    año: 1851,
  },
  {
    titulo: 'La muerte de Artemio Cruz',
    autor: 'Carlos Fuentes',
    genero: 'Ficción',
    año: 1962,
  },
  {
    titulo: 'El coronel no tiene quien le escriba',
    autor: 'Gabriel García Márquez',
    genero: 'Realismo mágico',
    año: 1961,
  },
  {
    titulo: 'Los cuatro vientos',
    autor: 'Kristin Hannah',
    genero: 'Ficción histórica',
    año: 2021,
  },
  {
    titulo: 'La insoportable levedad del ser',
    autor: 'Milan Kundera',
    genero: 'Ficción',
    año: 1984,
  },
  {
    titulo: 'La naranja mecánica',
    autor: 'Anthony Burgess',
    genero: 'Ciencia ficción',
    año: 1962,
  },
  {
    titulo: 'El gran teatro del mundo',
    autor: 'Pedro Calderón de la Barca',
    genero: 'Teatro',
    año: 1655,
  },
  {
    titulo: 'El jardín de los cerezos',
    autor: 'Antón Chéjov',
    genero: 'Teatro',
    año: 1904,
  },
  {
    titulo: 'La muerte en Venecia',
    autor: 'Thomas Mann',
    genero: 'Ficción',
    año: 1912,
  },
  {
    titulo: 'El tango de la guardia vieja',
    autor: 'Arturo Pérez-Reverte',
    genero: 'Ficción',
    año: 2012,
  },
  {
    titulo: 'El nombre de la rosa',
    autor: 'Umberto Eco',
    genero: 'Ficción histórica',
    año: 1980,
  },
];

console.log(listaDeLibros);
